### PR TITLE
Using the existing CACHE_DOMAINS_BRANCH and CACHE_DOMAINS_REPO Variable

### PR DESCRIPTION
**Pull request by b-reich**
Using the allready existing Variables.

Maybe this would be need as a feature for the runtime.

### CODE REVIEW

**Comment by VibroAxe** [comment]
This RUN line is only run once during the docker build steps, so the ENV vars will only ever be the defaults. Not sure this gains us anything?

The single branch change might make some sense though?

**Comment by b-reich** [comment]
Its not a big benefit thats true. The variables were already there.
Pulling a fresh list of Domains at start time or periodically, would be a nice improvement I think.

**Comment by VibroAxe** [comment]
> Its not a big benefit thats true. The variables were already there. Pulling a fresh list of Domains at start time or periodically, would be a nice improvement I think.

This is exactly what is already done, each time monolithic starts up it will pull the latest cache-domains from repo. It's handled here https://github.com/lancachenet/monolithic/blob/a45516468d9dd5dd7b96cdf311c07adb472c4e7f/overlay/hooks/entrypoint-pre.d/15_generate_maps.sh#L17

**Comment by b-reich** [comment]
Ahh okay. Thank you for the clarification.

Using the variables in the Dockerfile is still usefull I think. But its not a big deal to changes the values in 2 spots in the same file.

**Pull request closed without merging**
